# GPL (C) 1998 Andreas Tille
#   tille@debian.org

pixmapdir = $(prefix)/share/xteddy

pixmap_DATA = teddy.png xteddy.png xpenguin.png xduck.png xtuxxy.png \
              xalex.png xbobo.png xklitze.png xruessel.png xnamu.png xbrummi.png \
	      xorca.png \
	      xcherubino.png xhedgehog.png xpuppy.png xtrouble.png

EXTRA_DIST = $(pixmap_DATA) icons
